# Generated by Django 5.0.6 on 2024-06-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
