# Generated by Django 5.0.6 on 2024-06-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_rename_user_phone_tbl_user_user_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
