# Generated by Django 5.0.6 on 2024-06-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
