# Generated by Django 5.0.6 on 2024-06-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_shop_shop_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_shop',
            old_name='shop_phone',
            new_name='shop_contact',
        ),
    ]
