# Generated by Django 5.0.6 on 2024-06-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0013_rename_shop_phone_tbl_shop_shop_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_shop',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
