# Generated by Django 5.0.6 on 2024-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_tbl_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_shop',
            name='shop_status',
            field=models.IntegerField(default=0),
        ),
    ]
